version: "3.9"
services:
  db:
    image: postgres:16
    container_name: goida_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goida
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./app   # здесь Dockerfile для бэка
    container_name: goida_backend
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: goida
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
